# Análisis de Datos de Seguros - Enfoque Step-by-Step y Caso de Negocio

Este notebook está diseñado para que resuelvas problemas paso a paso utilizando Python (usando funciones básicas como .mean(), filtros, value_counts y groupby) y que puedas comparar los resultados con el objetivo propuesto. Además, se plantea un caso de negocio ficticio en el que se asigna un gasto en marketing (CAC) para evaluar la rentabilidad y tomar decisiones estratégicas.

El objetivo es evaluar tu habilidad para:
- Explorar y analizar datos en Python.
- Resolver problemas de análisis paso a paso.
- Comparar resultados con objetivos estratégicos.
- Formular conclusiones y recomendaciones basadas en los datos.

¡Comencemos!

In [15]:
!wget https://github.com/javierherrera1996/IntroMarketingAnalytics/raw/refs/heads/main/PrimerCorte/WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv.zip
!unzip WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv.zip

--2025-03-12 23:58:19--  https://github.com/javierherrera1996/IntroMarketingAnalytics/raw/refs/heads/main/PrimerCorte/WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv.zip
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/javierherrera1996/IntroMarketingAnalytics/refs/heads/main/PrimerCorte/WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv.zip [following]
--2025-03-12 23:58:19--  https://raw.githubusercontent.com/javierherrera1996/IntroMarketingAnalytics/refs/heads/main/PrimerCorte/WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 352796 (345K) [application/zip]
Saving to: ‘WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv.zip.1’

WA_Fn-UseC_-Marketi 100%[===================>] 344.53K  --.-KB/s    in 0.04s

2025-03-12 23:58:19 (7.85 MB/s) - ‘WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv.zip.1’ saved [352796/352796]

Archive:  WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv.zip
replace WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

## Paso 1: Exploración Inicial del Dataset
1. Carga el dataset `WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv`.
2. Revisa las primeras filas, dimensiones y la información general del dataset.

_Observa la estructura de los datos: ¿Qué columnas tienes? ¿Se nota algún dato atípico?_

In [16]:
# Cargar el dataset y ver primeras filas
import pandas as pd
import numpy as np

df = pd.read_csv('WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv')
pd.set_option('display.max_columns', None)

In [ ]:
df.shape

(9134, 24)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9134 entries, 0 to 9133
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Customer                       9134 non-null   object
 1   State                          9134 non-null   object
 2   Customer Lifetime Value        9134 non-null   float64
 3   Response                       9134 non-null   object
 4   Coverage                       9134 non-null   object
 5   Education                      9134 non-null   object
 6   Effective To Date              9134 non-null   object
 7   EmploymentStatus               9134 non-null   object
 8   Gender                         9134 non-null   object
 9   Income                         9134 non-null   int64
 10  Location Code                  9134 non-null   object
 11  Marital Status                 9134 non-null   object
 12  Monthly Premium Auto           9134 non-null   int64
 13  Months Since Last Claim        9134 non-null   int64
 14  Months Since Policy Inception  9134 non-null   int64
 15  Number of Open Complaints      9134 non-null   int64
 16  Number of Policies             9134 non-null   int64
 17  Policy Type                    9134 non-null   object
 18  Policy                         9134 non-null   object
 19  Renew Offer Type               9134 non-null   object
 20  Sales Channel                  9134 non-null   object
 21  Total Claim Amount             9134 non-null   float64
 22  Vehicle Class                  9134 non-null   object
 23  Vehicle Size                   9134 non-null   object
dtypes: float64(2), int64(6), object(16)
memory usage: 1.7+ MB

In [ ]:
df.head()

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,Suburban,Married,69,32,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,Suburban,Single,94,13,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,Suburban,Married,108,18,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,Suburban,Married,106,18,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2/3/11,Employed,M,43836,Rural,Single,73,12,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize

## Paso 2: Análisis del Customer Lifetime Value (CLV)
1. Calcula el CLV promedio y su desviación estándar.
2. Reflexiona: ¿Qué indica una alta desviación? ¿Podrían existir segmentos de clientes con comportamientos muy distintos?

Una alta desviación puede arrojar que existe una variabilidad significativa en los comportamientos de los clientes, entonces en este caso sí existe esa diferenciación entre clientes.

In [19]:
FL = df['Customer Lifetime Value'].mean()
FL
#este es el promedio

8004.940474987081

In [20]:
HH = df['Customer Lifetime Value'].std()
HH
#esta es la desviacion

6870.967608356924

## Paso 3: Evaluación de la Columna Response
1. Usa `value_counts()` para ver cuántos clientes respondieron "Yes" y "No".
2. Calcula el porcentaje de respuestas "Yes".

Pregunta: ¿La proporción de "Yes" es baja? ¿Qué podría indicar esto respecto a la estrategia de respuesta?

In [ ]:
df.Response.value_counts()

Response
No     7826
Yes    1308
Name: count, dtype: int64

Si, la proporción de YES es baja en comparación con la de NO. Esto podría indicar que la estrategia de respuesta debe ajustarse.

## Paso 4: Análisis de la Prima Mensual (Monthly Premium Auto) por Coverage
1. Agrupa los datos por `Coverage` y calcula la media de `Monthly Premium Auto`.
2. Compara los promedios obtenidos para cada tipo de Coverage.

Pregunta: ¿Existen diferencias notables entre las coberturas? ¿Qué implicaciones tendría esto en la estrategia de precios?

In [21]:
df.groupby('Coverage')['Monthly Premium Auto'].mean()

Coverage
Basic        82.173851
Extended    103.579504
Premium     133.381068
Name: Monthly Premium Auto, dtype: float64

**Paso 5:**
Agrupa los datos por EmploymentStatus y calcula el ingreso promedio.

Pregunta: ¿Qué diferencias encuentras entre los grupos? ¿Cómo podría influir esto en la segmentación de clientes?

In [33]:
df.groupby('EmploymentStatus')['Income'].mean()

EmploymentStatus
Disabled         20045.582716
Employed         56384.884521
Medical Leave    20292.770833
Retired          20554.960993
Unemployed           0.000000
Name: Income, dtype: float64

Las diferencias en los ingresos según el estado laboral tienen un impacto directo en la capacidad de compra y en las estrategias de segmentación.

## Paso 6: Análisis del CLV por Estado
1. Agrupa los datos por `State` y calcula el CLV promedio.

Pregunta: ¿Qué estado muestra el mayor CLV? ¿Qué factores regionales podrían explicar esto?

El estado de Oregon muestra el mayor CLV, pues puede tener una población con mayores ingresos promedio o una mayor capacidad económica en comparación con otros estados.

In [23]:
df.groupby('State')['Customer Lifetime Value'].mean()

State
Arizona       7861.341489
California    8003.647758
Nevada        8056.706839
Oregon        8077.901191
Washington    8021.472273
Name: Customer Lifetime Value, dtype: float64

## Paso 7: Análisis del Total Claim Amount según el Número de Pólizas
1. Separa a los clientes con más de 1 póliza de aquellos con 1 sola póliza.
2. Calcula el Total Claim Amount promedio para cada grupo.

Pregunta: ¿Qué diferencias encuentras y qué podrían indicar respecto al riesgo y comportamiento de reclamaciones?

In [24]:
# prompt: Separa a los clientes con más de 1 póliza de aquellos con 1 sola póliza.
# Calcula el Total Claim Amount promedio para cada grupo.

# Group data by 'Number of Policies' and calculate the average 'Total Claim Amount' for each group
policy_claim_amount = df.groupby('Number of Policies')['Total Claim Amount'].mean()
policy_claim_amount

Number of Policies
1    440.278532
2    433.610653
3    415.969821
4    428.791219
5    428.755107
6    410.962617
7    468.401546
8    445.049999
9    424.499642
Name: Total Claim Amount, dtype: float64

Las reclamaciones se mantienen dentro del mismo rango, están casi iguales sin importar el número de pólizas, lo que puede indicar un comportamiento estándar asociado al servicio más no a la cantidad de pólizas adquiridas.

## Paso 8: Análisis del CLV según Vehicle Class
1. Agrupa los datos por `Vehicle Class` y calcula el CLV promedio para cada clase.

Pregunta: ¿Qué clase de vehículo se asocia a un mayor CLV y qué implicaciones podría tener esto en la estrategia de producto?

In [25]:
df.groupby('Vehicle Class')['Customer Lifetime Value'].mean()

Vehicle Class
Four-Door Car     6631.726607
Luxury Car       17053.348399
Luxury SUV       17122.999134
SUV              10443.511816
Sports Car       10750.989331
Two-Door Car      6671.030732
Name: Customer Lifetime Value, dtype: float64

El luxury SUV se asocia a un mayor CLV, por lo que en la estrategia de producto, la compañía podría darle prioridad a este tipo de clientes, pues le representan más valor. Así mismo, encontrar la estrategia que mejor funcione y adaptarla a los demás vehículos.

## Paso 9: Análisis de Months Since Last Claim según Education
1. Agrupa los datos por `Education` y calcula el promedio de `Months Since Last Claim`.

Pregunta: ¿Existen diferencias notables entre los niveles educativos? ¿Qué podría indicar sobre la gestión de reclamos?

In [26]:
df.groupby('Education')['Months Since Last Claim'].mean()

Education
Bachelor                14.834789
College                 15.432301
Doctor                  15.260234
High School or Below    14.978642
Master                  15.199730
Name: Months Since Last Claim, dtype: float64

No existe una diferencia tan notable, los de nivel College, Doctor y Master están arriba y High School or Below y Bachelor son una cantidad un poco más baja, lo que puede sugerir que el público tiene un conocimiento base sólido para hacer sus reclamaciones a la compañía.

## Paso 10: Análisis del Income según Marital Status y Gender
1. Realiza una segmentación cruzada agrupando por `Marital Status` y `Gender` para calcular el ingreso promedio.

Pregunta: ¿Qué diferencias observas? ¿Cómo podrían influir estas diferencias en la estrategia de segmentación de clientes?

In [27]:
df.groupby(['Marital Status', 'Gender'])['Income'].mean()

Marital Status  Gender
Divorced        F         37913.709450
                M         43681.934848
Married         F         44276.994962
                M         43304.110361
Single          F         23573.758120
                M         22005.776407
Name: Income, dtype: float64

El género masculino tiene más ingresos cuando está divorciado, pero en el caso de casados y solteros, la mujer cuenta con un ingreso un poco mayor. Sin embargo, en los dos géneros hay ingresos menores cuando están solteros. Por esta razón, a los solteros pueden sugerirles pólizas más asequibles, mientras que a los divorciados y casados, pueden segmentarlos con pólizas más robustas.

## Paso 11: Distribución de la Columna Response
1. Usa `value_counts()` para mostrar cuántos clientes hay en cada grupo de Response.

Pregunta: ¿La distribución de respuestas sugiere que se debe ajustar la estrategia de comunicación?

In [28]:
df.Response.value_counts()

Response
No     7826
Yes    1308
Name: count, dtype: int64

La distribución de respuestas sugiere que si se debe ajustar la estrategia de comunicación, puesto que, son más las personas que se niegan a la póliza, lo que afecta la competitividad de la compañía.

## Paso 12: Análisis de Quejas Abiertas por Coverage
1. Agrupa los datos por `Coverage` y calcula el número promedio de quejas abiertas (`Number of Open Complaints`).

Pregunta: ¿Existen coberturas con un número de quejas significativamente mayor? ¿Qué acciones se podrían tomar?

In [29]:
df.groupby('Coverage')['Number of Open Complaints'].mean()

Coverage
Basic       0.384698
Extended    0.398979
Premium     0.333738
Name: Number of Open Complaints, dtype: float64

La cobertura Extended presenta un número de quejas significativamente mayor, por lo que se debe implementar una estrategia más potente de atención al cliente y de mejora del servicio para disminuir esta tasa.

## Paso 13: Análisis de la Antigüedad de las Pólizas según EmploymentStatus
1. Agrupa por `EmploymentStatus` y calcula el promedio de `Months Since Policy Inception`.

Pregunta: ¿Existe alguna relación entre el estado laboral y la antigüedad de las pólizas? ¿Qué podría implicar esto en la estabilidad del cliente?

In [30]:
df.groupby('EmploymentStatus')['Months Since Policy Inception'].mean()

EmploymentStatus
Disabled         47.469136
Employed         47.800456
Medical Leave    48.141204
Retired          48.531915
Unemployed       48.747087
Name: Months Since Policy Inception, dtype: float64

Aunque la antiguedad de las pólizas no muestra grandes diferencias, el estado laboral podría influir en la capacidad del cliente para mantener una póliza activa o para realizar pagos.

## Paso 14: Análisis del Total Claim Amount según Policy Type
1. Agrupa por `Policy Type` y calcula el Total Claim Amount promedio para cada tipo de póliza.

Pregunta: ¿Qué diferencias se observan entre los tipos de póliza y qué podrían implicar en términos de riesgo y eficiencia operativa?

In [31]:
df.groupby('Policy Type')['Total Claim Amount'].mean()

Policy Type
Corporate Auto    430.312188
Personal Auto     434.828219
Special Auto      440.472770
Name: Total Claim Amount, dtype: float64

Los vehículos corporativos tienden a generar menos reclamos, posiblemente debido a un manejo más controlado y un mantenimiento adecuado. En cambio, los vehículos personales y especiales, con mayores montos de reclamos, implican un mayor riesgo. Las pólizas de Corporate Auto parecen ser más eficientes operativamente, ya que los riesgos son menores. Las pólizas de Special Auto presentan mayor riesgo y reclamos superiores, lo que podría reducir la eficiencia operativa.

## Caso de Negocio: Evaluación de la Inversión en Marketing

### Contexto:
Una compañía de seguros ha asignado un presupuesto ficticio de **$5,000,000** para campañas de adquisición. El objetivo es evaluar la rentabilidad de la inversión comparando el gasto de marketing ( 50000000) (CAC) con el Customer Lifetime Value (CLV) obtenido.

### Tareas:
1. Utiliza el CLV promedio obtenido en el Paso 2.
2. Calcula el CAC promedio dividiendo el presupuesto de marketing entre el número total de clientes.
3. Compara el CAC promedio con el CLV promedio y responde:
   - ¿El CAC es inferior al CLV, lo que justificaría la inversión?
   - ¿Qué porcentaje del CLV representa el CAC?

_Reflexión estratégica: Si el CAC es significativamente menor que el CLV, la inversión en marketing es rentable. De lo contrario, se deberá replantear la estrategia de adquisición._

In [71]:
CLVprom = df['Customer Lifetime Value'].mean()
PKM = 5000000
Noclientes = len(df)

In [72]:
CAC = PKM/Noclientes

In [74]:
CLVprom

8004.940474987081

In [75]:
CAC

547.4052988832932

El CAC es inferior al CLV, entonces se justifica la inversión de marketing.

In [76]:
porcentaje_CAC_CLV = (CAC / CLVprom) * 100
porcentaje_CAC_CLV

6.838343153128526

El CAC representa el 6.83% del CLV.

### **Bonus:** Teniendo lo anterior en cual es la proporcion de clientes rentables

## Conclusiones y Recomendaciones

### **Bonus 2:** En no más de un parrafo mencione 3 acciones concretas para mejorar los reusltados de la empresa.